# Generated by Django 5.2 on 2025-04-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_title', models.CharField(max_length=255)),
                ('species_group', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('effectiveness_score', models.IntegerField()),
                ('evidence_type', models.CharField(choices=[('Experimental', 'Experimental'), ('Observational', 'Observational'), ('Review', 'Review')], max_length=20)),
                ('brief_outcome', models.TextField()),
            ],
        ),
    ]
